# Generated by Django 4.2.9 on 2024-01-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dokter', models.CharField(max_length=100)),
                ('tgl_pekerjaan', models.DateField()),
                ('spesialis', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'dokter',
            },
        ),
        migrations.CreateModel(
            name='Hewan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_hewan', models.CharField(max_length=100)),
                ('tgl_lahir', models.DateField()),
                ('tipe_hewan', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'hewan',
            },
        ),
        migrations.CreateModel(
            name='Klinik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_klinik', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('no_kontak', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'klinik',
            },
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_obat', models.CharField(max_length=100)),
                ('instruksi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'obat',
            },
        ),
        migrations.CreateModel(
            name='Pemilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemilik', models.CharField(max_length=100, unique=True)),
                ('no_kontak', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'pemilik',
            },
        ),
        migrations.CreateModel(
            name='Pemeriksaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('tgl_pemeriksaan', models.DateField()),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sik.dokter')),
                ('hewan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sik.hewan')),
                ('klinik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sik.klinik')),
            ],
            options={
                'verbose_name_plural': 'pemeriksaan',
            },
        ),
        migrations.CreateModel(
            name='Pem_obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=100)),
                ('frekuensi', models.CharField(max_length=100)),
                ('hewan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sik.hewan')),
                ('obat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sik.obat')),
                ('pemeriksaan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sik.pemeriksaan')),
            ],
            options={
                'verbose_name_plural': 'pem_obat',
            },
        ),
        migrations.AddField(
            model_name='hewan',
            name='pemilik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sik.pemilik'),
        ),
        migrations.AddField(
            model_name='dokter',
            name='klinik',
            field=models.ManyToManyField(to='sik.klinik'),
        ),
    ]
